### ISSUE TITLE
[BUG]google無法登入

### ISSUE THREAD

**Issue by alpha4021** [mrbigmouth/acgn-stock#89]
在HTTPS訪問主頁面時依然卡在OAUTH。調了DEBUGGER後發現
```
Uncaught DOMException: Blocked a frame with origin "http://acgn-stock.com" from accessing a cross-origin frame.
    at http://acgn-stock.com/packages/oauth/end_of_popup_response.js:18:40
    
    at http://acgn-stock.com/packages/oauth/end_of_popup_response.js:37:3
```

**Comment by mrbigmouth** [comment]
已在剛才修復。
